//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parking.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Top 1000 * From CarContact Order by Id Desc.
        /// </summary>
        internal static string SQLGetDataAll {
            get {
                return ResourceManager.GetString("SQLGetDataAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From CarContact Where TimeIn &gt; #{0:yyyy-MM-dd 00:00:00}# And TimeIn &lt; #{1:yyyy-MM-dd 23:59:59}# Order by {2}.
        /// </summary>
        internal static string SQLGetDataBetweenDate {
            get {
                return ResourceManager.GetString("SQLGetDataBetweenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select * From CarContact Where Id = {0}.
        /// </summary>
        internal static string SQLGetDataByRecord {
            get {
                return ResourceManager.GetString("SQLGetDataByRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0} Set TimeOut = Now(),UpdateDate = Now() Where {1} = {2}.
        /// </summary>
        internal static string SQLUpdateCarOut {
            get {
                return ResourceManager.GetString("SQLUpdateCarOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Count(1) From CarContact Where {0} = &apos;{1}&apos; And TimeOut Is Null.
        /// </summary>
        internal static string SQLValidateCarOut {
            get {
                return ResourceManager.GetString("SQLValidateCarOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to บันทึกข้อมูล{0}เรียบร้อย.
        /// </summary>
        internal static string SuccessSaveData {
            get {
                return ResourceManager.GetString("SuccessSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีทะเบียนรถอยู่ในระบบ.
        /// </summary>
        internal static string WarningNoCarLicense {
            get {
                return ResourceManager.GetString("WarningNoCarLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไม่มีเลขบัตรผู้ติดต่อนี้.
        /// </summary>
        internal static string WarningNoCarVisitor {
            get {
                return ResourceManager.GetString("WarningNoCarVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกเลขบัตรผู้ติดต่อ.
        /// </summary>
        internal static string WarningNoInputCarVisitor {
            get {
                return ResourceManager.GetString("WarningNoInputCarVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกข้อมูลอย่างใดอย่างหนึ่ง.
        /// </summary>
        internal static string WarningNoInputCarVisitorAndCarLicense {
            get {
                return ResourceManager.GetString("WarningNoInputCarVisitorAndCarLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เลขบัตรผู้ติดต่อได้ถูกใช้ไปแล้ว.
        /// </summary>
        internal static string WarningNoInputCarVistorDuplicate {
            get {
                return ResourceManager.GetString("WarningNoInputCarVistorDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกบ้านเลขที่.
        /// </summary>
        internal static string WarningNoInputContact {
            get {
                return ResourceManager.GetString("WarningNoInputContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกทะเบียนรถ.
        /// </summary>
        internal static string WarningNoInputLicensePlate {
            get {
                return ResourceManager.GetString("WarningNoInputLicensePlate", resourceCulture);
            }
        }
    }
}
